---
title: How to Read a Research Compendium
preprint: true
author: 
  - name: Daniel Nüst
    affiliation: 1
    corresponding: true
    email: daniel.nuest@uni-muenster.de
  #- name: Srinivasan Keshav
  #  affiliation: 2
  #  email: keshav@uwaterloo.ca
affiliation:
  - code: 1
    address: Institute for Geoinformatics, University of Münster, Münster, Germany
  #- code: 2
  #  address: David R. Cheriton School of Computer Science, University of Waterloo, Waterloo, ON, Canada
abstract: >
  _Researchers spend a great deal of time reading research papers._
  Keshav (2012) provides a three-pass method to researchers to improve their reading skills.
  This article extends Keshav's method to work for research compendia (RC).
  RC are an increasingly used form of publication packaging not only the research paper text and figures, but also all data and software used to conduct the computational workflow and create all outputs.
  We list the existing conventions for RC and suggest how to utilise their shared properties in a structured reading process.
  Unlike the original, this article is not build upon a long history but intends to provide guidance at the outset of an emerging practice.
header-includes: >
  \hypersetup{
    colorlinks,
    linkcolor={blue!50!black},
    citecolor={blue!50!black},
    urlcolor={blue!80!black}
  }
  \usepackage[normalem]{ulem}
bibliography: bibliography.bib
output:
  rticles::peerj_article:
    base_format: rmarkdown::pdf_document # bookdown::pdf_document2 # for using \@ref()
    keep_tex: yes
    number_sections: yes
---

<!-- Citations: @Figueredo:2009dg, citep: [@Figueredo:2009dg] -->
<!-- add " {-}" after headings to remove numbering -->

# 1. Introduction {-}

## 1.1 Motivation {-}

Research compendia (RC) are an increasingly used form of publications.
They comprise not only the research paper text and figures, but also all data and software used to conduct the computational workflow and create all outputs.
They provide a lot of added value but potentially also increase complexity for understanding, if not done well.
Therefore this work extends Keshav's three-pass method targeted at improving researcher's research paper reading skills [@keshav_how_2007] with additional steps to capture an RC's content.

Unlike the first version of the original [@keshav_how_2007], we cannot draw from a long history of experience.
But we intend to provide guidance at the outset of an emerging practice to both authors and readers of research compendia to understand each others perspectives and needs.
Authors may use this guide to improve their RC's structure and content, as they can better prepare for how readers may approach their work.
Readers may avoid the trap of falling too deep into technology challenges by an iterative reading approach.
This work may also improve the interaction between authors and mitigate unwarranted concerns, like giving support [@barnes_publish_2010]. 
Ultimately RCs can enhance and deepen the reading experience, if done right.
Keshav's following introduction applies directly to RCs:

> _Researchers must read papers for several reasons:_
> _to review  them  for  a  conference  or  a  class,  to  keep  current  in their field, or for a literature survey of a new field._
> _A typical researcher will likely spend hundreds of hours every year reading papers._
> 
> _Learning to efficiently read a paper is a critical but rarely taught skill._
> _Beginning graduate students, therefore, must learn  on  their  own  using  trial  and  error._
> _Students  waste much effort in the process and are frequently driven to frustration._
> 
> _For many years I have used a simple ‘three-pass’ approach to prevent me from drowning in the details of a paper before getting a bird’s-eye-view._
> _It allows me to estimate the amount of time required to review a set of papers._
> _Moreover, I can adjust the depth of paper evaluation depending on my needs and how much time I have._
> _This paper describes the approach and its use in doing a literature survey._ [@keshav_how_2016]

### 1.2 Structure {-}

In the remainder of this paper, the excellent original work that is taken over verbatim is in _italic font_ based on the most recent online version: @keshav_how_2016.
The term "paper" was not replaced with "research compendium" if no other changes were made in a paragraph.

First we briefly introduce research compendia and existing conventions, and also point out relevant publications as well as examples for authors of RCs.
Then, matching the original paper's section numbering, Sections 2 extends the "Three-pass Approach" to include RC features in the reading process.
Section 3 extends "Doing a Literature Survey" with aspects relevant reviewing many RCs.

### 1.3 Research compendia {-}

Term coined by @gentleman_statistical_2007.
RC improve transparency and quality of research [REF].
The code in science is good enough [@barnes_publish_2010].
RC improve citations [@vandevalle_code_2012].
RC answer scientists needs [@konkol_-depth_2018].

Briefly touch on (without doing a full literature study...)

- FAIR data
- Notebook science
- Computational environments
- Generic aspects of RC
  - "one click" / one wrapper / Makefile / main method
  - "Ten simple rules for..."
    - "Reproducible computational research" @sandve_ten_2013
    - "making research software more robust" @taschuk_ten_2017
    - "the Open Development of Scientific Software" @prlic_ten_2012
  - literate programming
  - scientific workflow systems
  - licensing @stodden_legal_2009

Add the RR/Open Science "pyramid"

**Conventions**

- https://github.com/ropensci/rrrpkg
- ERC: http://o2r.info/erc-spec
- rrtools (https://github.com/benmarwick/rrtools)
- @marwick_packaging_2017
- popper: http://falsifiable.us/ and @jimenez_popper_2017
- R packages, Python packages [@gentleman_statistical_2007]
- Researchcompendia.org [@stodden_researchcompendia.org:_2015]

# 2. The three-pass approach {-}

> _The key idea is that you should read the paper in up to three passes, instead of starting at the beginning and plowing your way to the end._
> _Each pass accomplishes specific goals  and  builds  upon  the  previous  pass:_
> _The first pass gives you a general idea about the paper._ 
> _The second pass lets you grasp the paper’s content, but not its details._ 
> _The third pass helps you understand the paper in depth._ [@keshav_how_2016]

## 2.1 The first pass {-}

> _The first pass is a quick scan to get a bird’s-eye view of the paper._
> _You can also decide whether you need to do any more passes._
> _This pass should take about five to ten minutes and consists of the following steps:_ [@keshav_how_2016]

1. _Carefully read the title, abstract, and introduction_
2. _Read the section and sub-section headings, but ignore everything else_
3. _Glance at the mathematical content (if any) to determine the underlying theoretical foundations_
4. _Read the conclusions_
5. _Glance over the references, mentally ticking off the ones you’ve already read_
6. Glance over the text looking for (a) URLs and `formatted` **names** referencing software and data (repositories) not yet mentioned in the sections read so far, mentally ticking off the ones you've heard about or used, and (b) tables or figures describing computational environments, deployments, or execution statistics
 
_At the end of the first pass, you should be able to answer the_ seven _Cs:_

1. _Category: What type of paper is this? A measurement paper? An analysis of an existing system? A description of a research prototype?_
2. _Context: Which other papers is it related to? Which theoretical bases were used to analyze the problem?_
3. _Correctness: Do the assumptions appear to be valid?_
4. _Contributions: What are the paper’s main contributions?_
5. _Clarity: Is the paper well written?_
6. Construction: What are the building blocks of the analysis workflow and how accessible are they (data set(s), programming language(s), tools, algorithms, scripts)? Under what licenses is the code published?
7. Complexity: What is the scale of the analysis (e.g. HPC, required OS/cores/memory, typical execution time, data size) and the software (number of dependencies and is installation possible with dependency management tools)?

> _Using this information, you may choose not to read further (and not print it out, thus saving trees)._
> _This could be because the paper doesn’t interest you, or you don’t know enough about the area to understand the paper, or that the authors make invalid assumptions._ [@keshav_how_2016]

You may also choose not to pursue the parts of the RC further, i.e. not looking at data, code, or running the workflow, thus saving resources.
Reasons related to code and data may be that you don't know have the expertise or resources to re-use data and code with acceptable efforts.

> _The first pass is adequate for papers that aren’t in your research area, but may someday prove relevant._ [@keshav_how_2016]

It suits RC comprising potentially re-usable components, like workflows or algorithms using data sets or generic software transferable to your field of research.
After the first pass, you should be able to judge if the software is useful if it works.

> _Incidentally, when you write a paper, you can expect most reviewers (and readers) to make only one pass over it._
> _Take care to choose coherent section and sub-section titles and to write concise and comprehensive abstracts._
> _If a reviewer cannot understand the gist after one pass, the paper will likely be rejected; if a reader cannot understand the highlights of the paper after five minutes, the paper will likely never be read._
> For these reasons, a ‘graphical abstract’ that summarizes a paper with a single well-chosen figure is an excellent idea and can be increasingly found in scientific journals._ [@keshav_how_2016]

Take also care to add instructions to reproduce your work and provide all required parts, i.e. publish a research compendium.
The instructions should start with a "blank" system to give readers an ideas what is needed to recreate your environment and execute the analysis, including expected or experienced execution times and resources.
If your work requires specialised or bespoke hardware (HPC, specific GPUs), consider creating an exemplary (reduced) analysis that runs in regular environments.

Also ensure your code and data is properly deposited, citable and licensed, or these core parts of your work will likely never be evaluated or re-used.
See Section "Research Compendia" for recommendations to make your reviewer's and reader's life easier.
However, every little bit helps and you should "find what works for you" even in reproducible research [@whitaker_publishing_2017].
It is better to come up with your own structure or solution, than providing no reproducible code or data at all.

## 2.2 The second pass {-}

> _In the second pass, read the paper with greater care, but ignore details such as proofs._
> _It helps to jot down the key points, or to make comments in the margins, as you read._
> _Dominik Grusemann from Uni Augsburg suggests that you "note down terms you didn’t understand, or questions you may want to ask the author."_
> _If you are acting as a paper referee, these comments will help you when you are writing your review, and to back up your review during the program committee meeting._  [@keshav_how_2016]
 
1. _Look carefully at the figures, diagrams and other illustrations in the paper. Pay special attention to graphs. Are the axes properly labeled?_
_Are results shown with error bars, so that conclusions are statistically significant? Common mistakes like these will separate rushed, shoddy work from the truly excellent._ [@keshav_how_2016]
1. _Remember to mark relevant unread references for further reading (this is a good way to learn more about the background of the paper)._ [@keshav_how_2016]
1. Skim over data and source code files. Are they reasonably named, or do they even follow a well-defined structure (e.g. a Python package or a research compendium convention)? Do they have comments? Is there a README file and/or structured documentation for functionalities?
1. Visit the source code repository, if available. Is it established and well maintained, or orphaned? Is there only one author or are there contributors? How responsive are they to issues? Does the repository have "stars" (i.e. public bookmarks) or forks? Are there regular releases, using semantic versioning?
1. Follow the instructions to execute the RC's workflow and compare the outputs with the ones reported in the paper. Note down errors or warnings during execution but do not try to fix any but trivial or known problems.
1. Check for differences in output figures. Do labels, legends etc. match?

The listing above gives a lot of examples how to estimate the quality of a software, but we recommend to be realistic as to what to expect and careful not to judge too fast.
The software project you evaluate might be done by a researcher under a lot of pressure and have only a single user and use case.
It is OK not to document beyond the information required by the author, and the documentation might be provided quickly once you as an external user show interest.
Also, no recent changes or releases can also mean the software is stable and simply works!

> _The second pass should take up to an hour for an experienced reader._ [@keshav_how_2016]

This does not include the computation time of workflows in an RC.
Use this time to complete first passes for one or several other papers.
If the used software is familiar, you may attempt to reduce the computation time by subsetting data or simplifying the workflow.
As an author, consider adding a reduced example to your RC for easier access by readers.

You may do quick or obvious fixes that prohibit a successful workflow execution, like fixing a path or install an undocumented dependency.
However we do recommend not to dive too deep - it is the author's responsibility to guide you through her work.
You may also face unsolvable problems, like access to specific infrastructure.
But you should report issues, for example in the software's public code repository, if available.

> _After this pass, you should be able to grasp the content of the paper._ [@keshav_how_2016]

You should have re-executed the provided workflow or understand why you could not.
At this point you should be able to judge whether you might want to re-use parts of the analysis, i.e. software or data, for your own work.

> _You should be able to summarize the main thrust of the paper, with supporting evidence, to someone else._
> _This level of detail is appropriate for a paper in which you are interested, but does not lie in your research speciality._
> _Sometimes you won’t understand a paper even at the end of the second pass._
> _This may be because the subject matter is new to you, with unfamiliar terminology and acronyms._
> _Or the authors may use a proof or experimental technique that you don’t understand, so that the bulk of the paper is incomprehensible._
> _The paper may be poorly written with unsubstantiated assertions and numerous forward references._ [@keshav_how_2016]

The RC may have incomplete documentation, rely on unavailable (e.g. proprietary) software or data, or require infrastructure not available to you.
It may use a programming language or programming paradigms unknown to you.

> _Or it could just be that it’s late at night and you’re tired._
> _You can now choose to: (a) set the paper aside, hoping you don’t need to understand the material to be successful in your career, (b) return to the paper later, perhaps after reading background material or (c) persevere and go on to the third pass._ [@keshav_how_2016]

## 2.3 The third pass {-}

> _To fully understand a paper, particularly if you are a reviewer, requires a third pass._
> _The key to the third pass is to attempt to virtually re-implement the paper: that is, making the same assumptions as the authors, re-create the work._
> _By comparing this re-creation with the actual paper, you can easily identify not only a paper’s innovations, but also its hidden failings and assumptions._
> _This pass requires great attention to detail._ [@keshav_how_2016]

If a best practice for structuring data and code was followed, familiarise yourself with it now.

> _You should identify and challenge every assumption in every statement._
> _Moreover, you should think about how you yourself would present a particular idea._
> _This comparison of the actual with the virtual lends a sharp insight into the proof and presentation techniques in the paper and you can very likely add this to your repertoire of tools._ [@keshav_how_2016]

Take a close look at data, metadata, and code.
This can be a time consuming very close study of the materials.
If data is not publicly available, e.g. because it may contain identifying information about humans, decide if you have a reasonable request to contact the original authors and ask for data access.
Work though the examples and analysis scripts included in the RC.
Play close attention not only to code, but also to code comments as they should include helpful information.
A good entry point for your code read may be a "main" script (if provided by the author) or literate programming document.
If that is not given then start with the code creating the figures for the article (e.g. look for "`plot`" statements in the code) and trace your way back through the code until you reach a statement where the input data is read.
Your impression on the code may support or refute your impression of the quality of the article's text.

If you did not succeed before but the work is relevant for you, spend more time on getting the analysis to run on your computer and do not hesitate to contact the author of the paper of authors of used software.
For them it is a great experience to be contacted by an interested reader!

With respect to the analysis, you may re-implement core parts or the full workflow with a different software.
For example using a tool one you know but which was not used in the RC.
Does your code lead to the same results, or does it give different ones?
Can the differences be explained or are they not significant?
Note that such a replication is of very high value for scholarly publishing and you should share your results with the RC's authors and also with the scientific community.
Depending on the efforts you put in, write a blog post or even publish a replication ~~paper~~ research compendium for one or more evaluated RCs.

If a full replication is not feasible, explore the assumptions you challenge with data and code.
Play around with input parameters to get a feel for the changing results.
Create explorative plots for the data as if you would want to analyse it, without the knowledge of the existing workflow.
With your understanding of the code now you can also extend the application to a new problem or different dataset.
This deep evaluation of code and data increases your understanding of the author's reasoning and decisions, and may lead to new questions.

To make sure you can trace your own hands-on changes with the original code and configuration, we recommend initiating a local git repository.
You can create branches for specific explorations and easily reset to the original functional state.

> _During this pass, you should also jot down ideas for future work._
> _This pass can take many hours for beginners and more than an hour or two even for an experienced reader._
> _At the end of this pass, you should be able to reconstruct the entire structure of the paper from memory, as well as be able to identify its strong and weak points._
> _In particular, you should be able to pinpoint implicit assumptions, missing citations to relevant work, and potential issues with experimental or analytical techniques._ [@keshav_how_2016]

You should be able to come up with useful extensions of the used software stack and be able to judge the transferability and reusability of the analysis' building blocks.
You should most certainly have improved your programming skills by reading and evaluating other people's code or even trying to apply it to a new problem.

# 3. Doing a literature survey {-}

> _Paper reading skills are put to the test in doing a literature survey._
> _This will require you to read tens of papers, perhaps in an unfamiliar field._
> _What papers should you read?_
> _Here is how you can use the three-pass approach to help._
> _First, use an academic search engine such as Google Scholar or CiteSeer and some well-chosen keywords to find three to five recent highly-cited papers in the area. [@keshav_how_2016]

No search capability comparable to scientific articles exists for RC, though you can of course use generic and academic search engines. More and more journals encourage reproducible research and software and data publication, so that extending your search regular search with keywords such as "reproduction", "reproducible", "open data/software/code" may give improve your results.

In addition, you can search online platforms where RC may be published and tagged as an RC (`research-compendium`):

- GitHub label: https://github.com/topics/research-compendium
- Zenodo community: https://zenodo.org/communities/research-compendium

There is no journal specifically for research compendia yet, but the following ones feature reproducibility, computational studies, or openness in some way and can be a starting point if they fit your topic:

- _ReScience_: https://rescience.github.io/
- _Information Systems_ has a reproducibility editor and special track for invited reproducibility papers: https://www.journals.elsevier.com/information-systems/

A lateral approach takes advantage of the parts of a RC.
If you work with a specific software (tool, extension package, library) or data, find out the recommended way to cite it (and follow it yourself).
Most scientific software provides this information in their FAQ or might have a build in function to generate a citation, and scientific data is often accompanied by a "data paper" or published in repositories with citeable identifiers.

Then search for recent papers which cite the core software or data of interest.

> _Do one pass on each paper to get a sense of the work, then read their related work sections._
> _You will find a thumbnail summary of the recent work, and perhaps, if you are lucky, a pointer to a recent survey paper._
> _If you can find such a survey, you are done._
> _Read the survey, congratulating yourself on your good luck._
> _Otherwise,  in the second step,  find shared citations and repeated author names in the bibliography._
> _These are the key papers and researchers in that area._

You can also find shared software or data and use them as a seed for a next iteration.

> _Download the key papers and set them aside._
> _Then go to the websites of the key researchers and see where they’ve published recently._
> _That will help you identify the top conferences in that field because the best researchers usually publish in the top conferences._

Also check where they publish their code and data.
It will give you an idea where this community interacts online and even lead you to RC under development.

> _The third step is to go to the website for these top conferences and look through their recent proceedings._
> _A quick scan will usually identify recent high-quality related work._
> _These papers, along with the ones you set aside earlier, constitute the first version of your survey._
> _Make two passes through these papers._
> _If they all cite a key paper that you did not find earlier, obtain and read it, iterating as necessary._ [@keshav_how_2016]

If a majority cites or uses a key software, technology, or dataset, evaluate it.

# 4. Related work {-}

> _If you are reading a paper to do a review, you should also read Timothy Roscoe's paper on "Writing reviews for systems conferences" [@roscoe_writing_2007]._
> _If you’re planning to write a technical paper, you should refer both to Henning Schulzrinne's comprehensive web site [@schulzrinne_writing_nodate] and George Whitesides’s excellent overview of the process [@whitesides_whitesides_2004]._
> _Finally, Simon Peyton Jones has a website that covers the entire spectrum of research skills [@peyton_jones_simon_nodate]._
> _Iain H. McLean of Psychology, Inc. has put together a downloadable 'review matrix' that simplifies paper reviewing using the three-pass approach for papers in experimental psychology [@mclean_literature_2012], which can probably be used, with minor modifications, for papers in other areas._ [@keshav_how_2016]

We have extended this matrix to provide space for notes about software, data, results of the reproduction, and application of the methods.

WIP: https://github.com/nuest/how-to-read-a-research-compendium/issues/2

[//]: # (maybe add https://www.bmj.com/about-bmj/resources-readers/publications/how-read-paper)

# 5. Acknowledgments {-}

> _The first version of this document was drafted by my students: Hossein Falaki, Earl Oliver, and Sumair Ur Rahman._
> _My thanks to them._ 
> _I also benefited from Christophe Diot’s perceptive comments and Nicole Keshav’s eagle-eyed copy-editing._
> _I would like to make this a living document, updating it as I receive comments._
> _Please take a moment to email me any comments or suggestions for improvement._
> _Thanks to encouraging  feedback  from  many  correspondents over the years._ [@keshav_how_2016]

In the spirit of the original paper, we would like to make this a living document and invite readers to provide comments or suggestions for improvement via email, as part of this preprint, or on the GitHub repository: [https://github.com/nuest/how-to-read-a-research-compendium](https://github.com/nuest/how-to-read-a-research-compendium).
The repository also includes open questions and is where the paper's authors openly discuss.

# References {-}
